name: family_pics
version: 1.0.0
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
transformers:
- angular:
    ##Luke-crunchbang
    #dart_sdk: "/usr/lib/dart"
    ##dot
    #dart_sdk: "/opt/dart/dart-sdk"
    ##yakko
    dart_sdk: "/Applications/dart/dart-sdk"
    html_files:
      - lib/component/navbar/navbar.html
      - lib/component/photogrid/photogrid.html
